In [ ]:
import numpy as np
import keras
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [ ]:
path_true_fake ="True_Fake.csv"


# Read both files
df = pd.read_csv(path_true_fake, delimiter=",",
                 engine="python",
                 encoding='utf-8')



In [ ]:
df.columns

Index(['Unnamed: 0', 'text', 'label'], dtype='object')

In [ ]:
df

Unnamed: 0                                               text  label
0             0  Donald Trump just couldn t wish all Americans ...      0
1             1  House Intelligence Committee Chairman Devin Nu...      0
2             2  On Friday, it was revealed that former Milwauk...      0
3             3  On Christmas day, Donald Trump announced that ...      0
4             4  Pope Francis used his annual Christmas Day mes...      0
..          ...                                                ...    ...
195          95  WASHINGTON (Reuters) - The chairman of the U.S...      1
196          96  WASHINGTON (Reuters) - U.S. President Donald T...      1
197          97  The following statements were posted to the ve...      1
198          98  WASHINGTON (Reuters) - Two members of Presiden...      1
199          99  WASHINGTON (Reuters) - The U.S. Senate will no...      1

[200 rows x 3 columns]

In [ ]:
df.label.value_counts()

label
0    100
1    100
Name: count, dtype: int64

In [ ]:
data = df[['text', 'label']]

In [ ]:
data

text  label
0    Donald Trump just couldn t wish all Americans ...      0
1    House Intelligence Committee Chairman Devin Nu...      0
2    On Friday, it was revealed that former Milwauk...      0
3    On Christmas day, Donald Trump announced that ...      0
4    Pope Francis used his annual Christmas Day mes...      0
..                                                 ...    ...
195  WASHINGTON (Reuters) - The chairman of the U.S...      1
196  WASHINGTON (Reuters) - U.S. President Donald T...      1
197  The following statements were posted to the ve...      1
198  WASHINGTON (Reuters) - Two members of Presiden...      1
199  WASHINGTON (Reuters) - The U.S. Senate will no...      1

[200 rows x 2 columns]

In [ ]:
y = list(data['label'])

In [ ]:
# y

In [ ]:
# Word Vectorizing using TFIDF


documents=[]

for i in data['text']:
    s = str(i)
    documents.append(s)
vectorizer = TfidfVectorizer(stop_words='english')
x = vectorizer.fit_transform(documents)

In [ ]:
documents[0]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t ev

In [ ]:
x[0]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 169 stored elements and shape (1, 9080)>

In [ ]:
# x[0]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.20,
                                                    random_state=0)

In [ ]:
lr_clf = LogisticRegression()
lr_clf.fit(x_train, y_train)

LogisticRegression()

In [ ]:
lr_clf.score(x_test, y_test)

0.95

In [ ]:
lr_clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
!pip install sentence-transformers

In [ ]:
# Word Embeddings using BERT

documents_bert=[]

for i in data['text']:
    s = str(i)
    documents_bert.append(s)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/bert-base-nli-mean-tokens') #bert-base-nli-mean-tokens
embeddings = model.encode(documents_bert)
print(embeddings)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[-0.13895041  0.8994348   1.0744388  ... -0.01868415  0.21273223
   0.19466296]
 [-0.17545074  0.6811158  -0.10804953 ...  0.05777059 -0.5364269
   0.60426605]
 [-0.4084757   0.6238574   0.20368265 ... -0.14129111 -0.41535944
   0.28411674]
 ...
 [-0.41226527  0.5471734   0.3668832  ...  0.49663067  0.06506459
   0.19465835]
 [-0.5531323   0.20122078  0.328539   ...  0.50654817  0.5728783
  -0.10159883]
 [-0.3003424   0.41022748  0.59883016 ...  0.4967456  -0.31504104
   0.36200953]]


In [ ]:
documents_bert[0]

'Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year,  President Angry Pants tweeted.  2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America!  Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t ev

In [ ]:
embeddings[0]

array([-1.38950408e-01,  8.99434805e-01,  1.07443881e+00,  1.37262598e-01,
       -2.35424086e-01, -1.29622757e+00,  8.02027464e-01,  1.63255021e-01,
        4.50139582e-01, -1.36877939e-01, -3.95173222e-01,  6.93508208e-01,
       -2.20976830e-01,  2.48336375e-01, -7.01173782e-01,  2.35867396e-01,
        2.45977074e-01, -3.36722076e-01, -8.86924472e-03, -7.33049065e-02,
       -3.63070965e-01, -4.92682338e-01,  5.10451496e-01,  2.34742180e-01,
        1.18785417e+00,  2.02536985e-01, -5.32446980e-01, -4.19835508e-01,
       -8.26016903e-01,  6.40481710e-01,  2.12602057e-02,  6.28513992e-01,
       -9.55516577e-01,  1.15303881e-02, -7.84763396e-01,  1.42476678e+00,
        9.22479093e-01, -1.41619697e-01,  3.05612743e-01,  1.75162703e-02,
        1.99279964e-01, -2.59867221e-01, -3.25814813e-01, -2.84426808e-01,
       -1.01165450e+00, -4.75116193e-01,  8.28862190e-02,  5.25186956e-01,
        6.36917293e-01, -1.05375338e+00,  7.62224853e-01,  6.04949236e-01,
        3.80452648e-02, -

In [ ]:
embeddings.shape

(200, 768)

In [ ]:

train_features, test_features, train_labels, test_labels = train_test_split(embeddings, y, test_size = 0.20, random_state = 0)


In [ ]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(train_features, train_labels)

LogisticRegression()

In [ ]:
lr_clf.score(test_features, test_labels)

0.95

In [ ]:
inference_sentences = ['WASHINGTON (Reuters) Pierre-Emerick Aubameyang’s time at FC Barcelona may have been brief, but it was remarkably impactful.Joining the Catalan giants in January 2022, the Gabonese striker quickly became a fan favourite, scoring 13 goals in just 23 appearances across all competitions. His speed, clinical finishing, and energy revitalized Barcelona’s attack during a challenging period, helping the club secure a second-place finish in La Liga. However, his stint at Barcelona ended after just eight months when financial constraints forced the club to sell him to Chelsea.']
inference_sentences_embeddings = model.encode(inference_sentences)

In [ ]:
lr_clf.predict(inference_sentences_embeddings)

array([0])